// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAecol_CrDXtZZkknmG2Jvpo28exog7nAo",
    appId: "1:650736886798:web:ff1da2831eaa5ccc58885f",
    messagingSenderId: "650736886798",
    projectId: "pata-noteprice",
    authDomain: "pata-noteprice.firebaseapp.com",
    storageBucket: "pata-noteprice.firebasestorage.app",
    measurementId: "G-MZBCKLGN5D",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB1R_jm8lPrkzWDE6UaBNA9mSEd4jAObto",
    appId: "1:650736886798:android:406cb1abea05877c58885f",
    messagingSenderId: "650736886798",
    projectId: "pata-noteprice",
    storageBucket: "pata-noteprice.firebasestorage.app",
  );
}